# =========================================================
# Alembic Configuration for MakanAI
# =========================================================
# This file configures Alembic migration settings
#
# Note: sqlalchemy.url is overriden in alembic/env.py
# using the DATABASE URL from your .env file so no
# need to change it here
# =========================================================

[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = postgresql+psycopg2://postgres:1234@localhost:5432/makanai

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING 
handlers = console
qualname = 

[logger_sqlalchemy]
level = WARNING
handlers = 
qualname = sqlalchemy.engine 

[logger_alembic]
level = INFO 
handlers = 
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S