/** 
 * InsightsScreen 
 * 
 * Displays the user's weekly nutrition insight, generated by the 
 * insight_agent on the backend. Shows a date range, AI-written summary,
 * daily nutrition average, positive insights and suggestion 
 * 
 * Data flow:
 *  on mount -> GET /api/insights/weekly (with JWT)
 *           -> orchestrator -> insight_agent -> Ollama
 *           -> response rendered in cards
 *
 * Props: 
 *  token (string) - JWT access token, passed from AppShell
 * 
 * Used by: AppShell.jsx (when tab == 'insights')
 * 
 * Notes: 
 *  - First load can take 20-30s as Ollama warms up the phi3 model 
 *  - Uses a 'cancelled' flag to avoid setState on an unmounted 
 *    component if the user switches tab mid-fetch
 */

import { useState, useEffect } from 'react';
import { api } from '../api/client';
import Spinner from '../components/Spinner';
import NutriBadge from '../components/NutriBadge';

export default function InsightsScreen({ token }) {
  const [insight, setInsight] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    let cancelled = false;

    const load = async () => {
      setLoading(true);
      setError('');
      try {
        const data = await api.get('/api/insights/weekly', token);
        if (!cancelled) setInsight(data);
      } catch (err) {
        if (!cancelled) setError(err.message);
      } finally {
        if (!cancelled) setLoading(false);
      }
    };

    load();
    return () => { cancelled = true; };
  }, [token]);

  // ─── loading state ───────────────────────────
  if (loading) {
    return (
      <div style={{ padding: 60, textAlign: 'center', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 16 }}>
        <Spinner size={40} />
        <div style={{ fontFamily: 'Lora', fontStyle: 'italic', color: 'var(--ink-lt)', fontSize: 14 }}>
          Reading your week... this can take 20-30s on first load.
        </div>
      </div>
    );
  }

  // ─── error state ─────────────────────────────
  if (error) {
    return (
      <div style={{ padding: 40, maxWidth: 600, margin: '0 auto' }}>
        <div style={{
          background: '#FDE8E0',
          border: '1px solid var(--terra)',
          borderRadius: 8,
          padding: '12px 16px',
          fontSize: 13,
          color: 'var(--terra)',
          fontWeight: 600,
        }}>
          ⚠ {error}
        </div>
      </div>
    );
  }

  if (!insight) return null;

  const { week_start, week_end, total_meals, average_nutrition, summary, highlights, suggestions } = insight;

  return (
    <div style={{ padding: '32px 40px', maxWidth: 760, margin: '0 auto', width: '100%' }}>
      {/* ─── Heading ─── */}
      <div style={{ marginBottom: 24 }}>
        <h1 style={{
          fontFamily: 'Lora',
          fontStyle: 'italic',
          fontWeight: 700,
          fontSize: 32,
          color: 'var(--ink)',
        }}>
          Your Week 📊
        </h1>
        <p style={{ fontSize: 14, color: 'var(--ink-lt)', fontWeight: 600, marginTop: 4 }}>
          {formatDate(week_start)} — {formatDate(week_end)} · {total_meals} meals logged
        </p>
      </div>

      {/* ─── Summary card ─── */}
      <div className="card fadeUp" style={{ padding: 24, marginBottom: 18 }}>
        <div style={{
          fontSize: 11,
          fontWeight: 700,
          color: 'var(--ink-lt)',
          textTransform: 'uppercase',
          letterSpacing: 0.5,
          marginBottom: 10,
        }}>
          Summary
        </div>
        <p style={{
          fontFamily: 'Lora',
          fontStyle: 'italic',
          fontSize: 17,
          lineHeight: 1.6,
          color: 'var(--ink)',
          fontWeight: 500,
        }}>
          {summary}
        </p>
      </div>

      {/* ─── Daily averages ─── */}
      <div className="card fadeUp" style={{ padding: 24, marginBottom: 18 }}>
        <div style={{
          fontSize: 11,
          fontWeight: 700,
          color: 'var(--ink-lt)',
          textTransform: 'uppercase',
          letterSpacing: 0.5,
          marginBottom: 14,
        }}>
          Daily averages
        </div>
        <div style={{ display: 'flex', gap: 10, flexWrap: 'wrap' }}>
          <NutriBadge label="Calories" value={average_nutrition.calories} unit=" kcal" color="#FBE8C8" />
          <NutriBadge label="Protein"  value={average_nutrition.protein}  unit="g"     color="#F2E0C8" />
          <NutriBadge label="Carbs"    value={average_nutrition.carbs}    unit="g"     color="#D4E8D0" />
          <NutriBadge label="Fat"      value={average_nutrition.fat}      unit="g"     color="#E8D8F0" />
          <NutriBadge label="Fiber"    value={average_nutrition.fiber}    unit="g"     color="#FBE8C8" />
        </div>
      </div>

      {/* ─── Highlights ─── */}
      {highlights?.length > 0 && (
        <div className="card fadeUp" style={{ padding: 24, marginBottom: 18 }}>
          <div style={{
            fontSize: 11,
            fontWeight: 700,
            color: 'var(--sage)',
            textTransform: 'uppercase',
            letterSpacing: 0.5,
            marginBottom: 12,
          }}>
            ✓ Highlights
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {highlights.map((h, i) => (
              <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--sage)', fontSize: 16, flexShrink: 0, marginTop: 1 }}>✓</span>
                <span style={{ fontSize: 14, fontWeight: 500, color: 'var(--ink)', lineHeight: 1.6 }}>{h}</span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ─── Suggestions ─── */}
      {suggestions?.length > 0 && (
        <div className="card fadeUp" style={{ padding: 24, marginBottom: 18 }}>
          <div style={{
            fontSize: 11,
            fontWeight: 700,
            color: 'var(--gold)',
            textTransform: 'uppercase',
            letterSpacing: 0.5,
            marginBottom: 12,
          }}>
            → Suggestions
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
            {suggestions.map((s, i) => (
              <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                <span style={{ color: 'var(--gold)', fontSize: 16, flexShrink: 0, marginTop: 1 }}>→</span>
                <span style={{ fontSize: 14, fontWeight: 500, color: 'var(--ink)', lineHeight: 1.6 }}>{s}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
}

// ─── helper ───
function formatDate(isoDate) {
  if (!isoDate) return '';
  const d = new Date(isoDate);
  return d.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}